### ISSUE TITLE
Error loading file with survey data -- because float not supported?

### ISSUE THREAD

**Issue by kristinksellers** [catalystneuro/ndx-survey-data#14]
@Armin12  I'm able to write our behavior data using the survey data tables, but cannot load that file. Is this because floats are not supported? We have some missing values (and thus have NaNs represented in the survey data tables)

Error when trying to read NWB file below:

`---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
C:\Anaconda\envs\NWB\lib\site-packages\hdmf\build\objectmapper.py in construct(self, **kwargs)
   1000                               object_id=builder.attributes.get(self.__spec.id_key()))
-> 1001             obj.__init__(**kwargs)
   1002         except Exception as ex:

C:\Anaconda\envs\NWB\lib\site-packages\hdmf\utils.py in func_call(*args, **kwargs)
    479                     msg = '%s: %s' % (func.__qualname__, ', '.join(parse_err))
--> 480                     raise ExceptionType(msg)
    481 

TypeError: QuestionResponse.__init__: incorrect type for 'data' (got 'float64', expected 'ndarray, list, tuple, Dataset, HDMFDataset, AbstractDataChunkIterator or DataIO')

The above exception was the direct cause of the following exception:

Exception                                 Traceback (most recent call last)
<ipython-input-34-1115a7465a2c> in <module>
      7 
      8 io = NWBHDF5IO(toRead, 'r')
----> 9 nwbfile = io.read()

C:\Anaconda\envs\NWB\lib\site-packages\hdmf\backends\hdf5\h5tools.py in read(self, **kwargs)
    302                                        % (self.__path, self.__mode))
    303         try:
--> 304             return call_docval_func(super().read, kwargs)
    305         except UnsupportedOperation as e:
    306             if str(e) == 'Cannot build data. There are no values.':

C:\Anaconda\envs\NWB\lib\site-packages\hdmf\utils.py in call_docval_func(func, kwargs)
    362 def call_docval_func(func, kwargs):
    363     fargs, fkwargs = fmt_docval_args(func, kwargs)
--> 364     return func(*fargs, **fkwargs)
    365 
    366 

C:\Anaconda\envs\NWB\lib\site-packages\hdmf\utils.py in func_call(*args, **kwargs)
    481 
    482             if is_method:
--> 483                 return func(args[0], **parsed['args'])
    484             else:
    485                 return func(**parsed['args'])

C:\Anaconda\envs\NWB\lib\site-packages\hdmf\backends\io.py in read(self, **kwargs)
     33             # TODO also check that the keys are appropriate. print a better error message
     34             raise UnsupportedOperation('Cannot build data. There are no values.')
---> 35         container = self.__manager.construct(f_builder)
     36         return container
     37 

C:\Anaconda\envs\NWB\lib\site-packages\hdmf\utils.py in func_call(*args, **kwargs)
    481 
    482             if is_method:
--> 483                 return func(args[0], **parsed['args'])
    484             else:
    485                 return func(**parsed['args'])

C:\Anaconda\envs\NWB\lib\site-packages\hdmf\build\manager.py in construct(self, **kwargs)
    197                 # we are at the top of the hierarchy,
    198                 # so it must be time to resolve parents
--> 199                 result = self.__type_map.construct(builder, self, None)
    200                 self.__resolve_parents(result)
    201             self.prebuilt(result, builder)

C:\Anaconda\envs\NWB\lib\site-packages\hdmf\utils.py in func_call(*args, **kwargs)
    481 
    482             if is_method:
--> 483                 return func(args[0], **parsed['args'])
    484             else:
    485                 return func(**parsed['args'])

C:\Anaconda\envs\NWB\lib\site-packages\hdmf\build\manager.py in construct(self, **kwargs)
    768             raise ValueError('No ObjectMapper found for builder of type %s' % dt)
    769         else:
--> 770             return obj_mapper.construct(builder, build_manager, parent)
    771 
    772     @docval({"name": "container", "type": AbstractContainer, "doc": "the container to convert to a Builder"},

C:\Anaconda\envs\NWB\lib\site-packages\hdmf\utils.py in func_call(*args, **kwargs)
    481 
    482             if is_method:
--> 483                 return func(args[0], **parsed['args'])
    484             else:
    485                 return func(**parsed['args'])

C:\Anaconda\envs\NWB\lib\site-packages\hdmf\build\objectmapper.py in construct(self, **kwargs)
    967         cls = manager.get_cls(builder)
    968         # gather all subspecs
--> 969         subspecs = self.__get_subspec_values(builder, self.spec, manager)
    970         # get the constructor argument that each specification corresponds to
    971         const_args = dict()

C:\Anaconda\envs\NWB\lib\site-packages\hdmf\build\objectmapper.py in __get_subspec_values(self, builder, spec, manager)
    897                         ret[subspec] = self.__flatten(sub_builder, subspec, manager)
    898             # now process groups and datasets
--> 899             self.__get_sub_builders(groups, spec.groups, manager, ret)
    900             self.__get_sub_builders(datasets, spec.datasets, manager, ret)
    901         elif isinstance(spec, DatasetSpec):

C:\Anaconda\envs\NWB\lib\site-packages\hdmf\build\objectmapper.py in __get_sub_builders(self, sub_builders, subspecs, manager, ret)
    947                 if dt is None:
    948                     # recurse
--> 949                     ret.update(self.__get_subspec_values(sub_builder, subspec, manager))
    950                 else:
    951                     ret[subspec] = manager.construct(sub_builder)

C:\Anaconda\envs\NWB\lib\site-packages\hdmf\build\objectmapper.py in __get_subspec_values(self, builder, spec, manager)
    897                         ret[subspec] = self.__flatten(sub_builder, subspec, manager)
    898             # now process groups and datasets
--> 899             self.__get_sub_builders(groups, spec.groups, manager, ret)
    900             self.__get_sub_builders(datasets, spec.datasets, manager, ret)
    901         elif isinstance(spec, DatasetSpec):

C:\Anaconda\envs\NWB\lib\site-packages\hdmf\build\objectmapper.py in __get_sub_builders(self, sub_builders, subspecs, manager, ret)
    939                 sub_builder = builder_dt.get(dt)
    940                 if sub_builder is not None:
--> 941                     sub_builder = self.__flatten(sub_builder, subspec, manager)
    942                     ret[subspec] = sub_builder
    943             else:

C:\Anaconda\envs\NWB\lib\site-packages\hdmf\build\objectmapper.py in __flatten(self, sub_builder, subspec, manager)
    952 
    953     def __flatten(self, sub_builder, subspec, manager):
--> 954         tmp = [manager.construct(b) for b in sub_builder]
    955         if len(tmp) == 1 and not subspec.is_many():
    956             tmp = tmp[0]

C:\Anaconda\envs\NWB\lib\site-packages\hdmf\build\objectmapper.py in <listcomp>(.0)
    952 
    953     def __flatten(self, sub_builder, subspec, manager):
--> 954         tmp = [manager.construct(b) for b in sub_builder]
    955         if len(tmp) == 1 and not subspec.is_many():
    956             tmp = tmp[0]

C:\Anaconda\envs\NWB\lib\site-packages\hdmf\utils.py in func_call(*args, **kwargs)
    481 
    482             if is_method:
--> 483                 return func(args[0], **parsed['args'])
    484             else:
    485                 return func(**parsed['args'])

C:\Anaconda\envs\NWB\lib\site-packages\hdmf\build\manager.py in construct(self, **kwargs)
    193             if parent_builder is not None:
    194                 parent = self.__get_proxy_builder(parent_builder)
--> 195                 result = self.__type_map.construct(builder, self, parent)
    196             else:
    197                 # we are at the top of the hierarchy,

C:\Anaconda\envs\NWB\lib\site-packages\hdmf\utils.py in func_call(*args, **kwargs)
    481 
    482             if is_method:
--> 483                 return func(args[0], **parsed['args'])
    484             else:
    485                 return func(**parsed['args'])

C:\Anaconda\envs\NWB\lib\site-packages\hdmf\build\manager.py in construct(self, **kwargs)
    768             raise ValueError('No ObjectMapper found for builder of type %s' % dt)
    769         else:
--> 770             return obj_mapper.construct(builder, build_manager, parent)
    771 
    772     @docval({"name": "container", "type": AbstractContainer, "doc": "the container to convert to a Builder"},

C:\Anaconda\envs\NWB\lib\site-packages\hdmf\utils.py in func_call(*args, **kwargs)
    481 
    482             if is_method:
--> 483                 return func(args[0], **parsed['args'])
    484             else:
    485                 return func(**parsed['args'])

C:\Anaconda\envs\NWB\lib\site-packages\hdmf\build\objectmapper.py in construct(self, **kwargs)
    967         cls = manager.get_cls(builder)
    968         # gather all subspecs
--> 969         subspecs = self.__get_subspec_values(builder, self.spec, manager)
    970         # get the constructor argument that each specification corresponds to
    971         const_args = dict()

C:\Anaconda\envs\NWB\lib\site-packages\hdmf\build\objectmapper.py in __get_subspec_values(self, builder, spec, manager)
    897                         ret[subspec] = self.__flatten(sub_builder, subspec, manager)
    898             # now process groups and datasets
--> 899             self.__get_sub_builders(groups, spec.groups, manager, ret)
    900             self.__get_sub_builders(datasets, spec.datasets, manager, ret)
    901         elif isinstance(spec, DatasetSpec):

C:\Anaconda\envs\NWB\lib\site-packages\hdmf\build\objectmapper.py in __get_sub_builders(self, sub_builders, subspecs, manager, ret)
    939                 sub_builder = builder_dt.get(dt)
    940                 if sub_builder is not None:
--> 941                     sub_builder = self.__flatten(sub_builder, subspec, manager)
    942                     ret[subspec] = sub_builder
    943             else:

C:\Anaconda\envs\NWB\lib\site-packages\hdmf\build\objectmapper.py in __flatten(self, sub_builder, subspec, manager)
    952 
    953     def __flatten(self, sub_builder, subspec, manager):
--> 954         tmp = [manager.construct(b) for b in sub_builder]
    955         if len(tmp) == 1 and not subspec.is_many():
    956             tmp = tmp[0]

C:\Anaconda\envs\NWB\lib\site-packages\hdmf\build\objectmapper.py in <listcomp>(.0)
    952 
    953     def __flatten(self, sub_builder, subspec, manager):
--> 954         tmp = [manager.construct(b) for b in sub_builder]
    955         if len(tmp) == 1 and not subspec.is_many():
    956             tmp = tmp[0]

C:\Anaconda\envs\NWB\lib\site-packages\hdmf\utils.py in func_call(*args, **kwargs)
    481 
    482             if is_method:
--> 483                 return func(args[0], **parsed['args'])
    484             else:
    485                 return func(**parsed['args'])

C:\Anaconda\envs\NWB\lib\site-packages\hdmf\build\manager.py in construct(self, **kwargs)
    193             if parent_builder is not None:
    194                 parent = self.__get_proxy_builder(parent_builder)
--> 195                 result = self.__type_map.construct(builder, self, parent)
    196             else:
    197                 # we are at the top of the hierarchy,

C:\Anaconda\envs\NWB\lib\site-packages\hdmf\utils.py in func_call(*args, **kwargs)
    481 
    482             if is_method:
--> 483                 return func(args[0], **parsed['args'])
    484             else:
    485                 return func(**parsed['args'])

C:\Anaconda\envs\NWB\lib\site-packages\hdmf\build\manager.py in construct(self, **kwargs)
    768             raise ValueError('No ObjectMapper found for builder of type %s' % dt)
    769         else:
--> 770             return obj_mapper.construct(builder, build_manager, parent)
    771 
    772     @docval({"name": "container", "type": AbstractContainer, "doc": "the container to convert to a Builder"},

C:\Anaconda\envs\NWB\lib\site-packages\hdmf\utils.py in func_call(*args, **kwargs)
    481 
    482             if is_method:
--> 483                 return func(args[0], **parsed['args'])
    484             else:
    485                 return func(**parsed['args'])

C:\Anaconda\envs\NWB\lib\site-packages\hdmf\build\objectmapper.py in construct(self, **kwargs)
    967         cls = manager.get_cls(builder)
    968         # gather all subspecs
--> 969         subspecs = self.__get_subspec_values(builder, self.spec, manager)
    970         # get the constructor argument that each specification corresponds to
    971         const_args = dict()

C:\Anaconda\envs\NWB\lib\site-packages\hdmf\build\objectmapper.py in __get_subspec_values(self, builder, spec, manager)
    898             # now process groups and datasets
    899             self.__get_sub_builders(groups, spec.groups, manager, ret)
--> 900             self.__get_sub_builders(datasets, spec.datasets, manager, ret)
    901         elif isinstance(spec, DatasetSpec):
    902             if not isinstance(builder, DatasetBuilder):

C:\Anaconda\envs\NWB\lib\site-packages\hdmf\build\objectmapper.py in __get_sub_builders(self, sub_builders, subspecs, manager, ret)
    939                 sub_builder = builder_dt.get(dt)
    940                 if sub_builder is not None:
--> 941                     sub_builder = self.__flatten(sub_builder, subspec, manager)
    942                     ret[subspec] = sub_builder
    943             else:

C:\Anaconda\envs\NWB\lib\site-packages\hdmf\build\objectmapper.py in __flatten(self, sub_builder, subspec, manager)
    952 
    953     def __flatten(self, sub_builder, subspec, manager):
--> 954         tmp = [manager.construct(b) for b in sub_builder]
    955         if len(tmp) == 1 and not subspec.is_many():
    956             tmp = tmp[0]

C:\Anaconda\envs\NWB\lib\site-packages\hdmf\build\objectmapper.py in <listcomp>(.0)
    952 
    953     def __flatten(self, sub_builder, subspec, manager):
--> 954         tmp = [manager.construct(b) for b in sub_builder]
    955         if len(tmp) == 1 and not subspec.is_many():
    956             tmp = tmp[0]

C:\Anaconda\envs\NWB\lib\site-packages\hdmf\utils.py in func_call(*args, **kwargs)
    481 
    482             if is_method:
--> 483                 return func(args[0], **parsed['args'])
    484             else:
    485                 return func(**parsed['args'])

C:\Anaconda\envs\NWB\lib\site-packages\hdmf\build\manager.py in construct(self, **kwargs)
    193             if parent_builder is not None:
    194                 parent = self.__get_proxy_builder(parent_builder)
--> 195                 result = self.__type_map.construct(builder, self, parent)
    196             else:
    197                 # we are at the top of the hierarchy,

C:\Anaconda\envs\NWB\lib\site-packages\hdmf\utils.py in func_call(*args, **kwargs)
    481 
    482             if is_method:
--> 483                 return func(args[0], **parsed['args'])
    484             else:
    485                 return func(**parsed['args'])

C:\Anaconda\envs\NWB\lib\site-packages\hdmf\build\manager.py in construct(self, **kwargs)
    768             raise ValueError('No ObjectMapper found for builder of type %s' % dt)
    769         else:
--> 770             return obj_mapper.construct(builder, build_manager, parent)
    771 
    772     @docval({"name": "container", "type": AbstractContainer, "doc": "the container to convert to a Builder"},

C:\Anaconda\envs\NWB\lib\site-packages\hdmf\utils.py in func_call(*args, **kwargs)
    481 
    482             if is_method:
--> 483                 return func(args[0], **parsed['args'])
    484             else:
    485                 return func(**parsed['args'])

C:\Anaconda\envs\NWB\lib\site-packages\hdmf\build\objectmapper.py in construct(self, **kwargs)
   1002         except Exception as ex:
   1003             msg = 'Could not construct %s object due to: %s' % (cls.__name__, ex)
-> 1004             raise Exception(msg) from ex
   1005         return obj
   1006 

Exception: Could not construct QuestionResponse object due to: QuestionResponse.__init__: incorrect type for 'data' (got 'float64', expected 'ndarray, list, tuple, Dataset, HDMFDataset, AbstractDataChunkIterator or DataIO')`

**Comment by Armin12** [comment]
It seems that the error occurs because of the type of NaN values fed to the VectorData. Could you try np.nan to represent NaN values?

**Comment by kristinksellers** [comment]
@Armin12 The NaN values previously were represented as numpy.float64.  

I'm trying to replace as np.nan (see lines below), but they are still type float64 in the dataframe, and the error still occurs upon trying to load the NWB file

`df_redcap.fillna(value = np.nan, inplace = True)`
OR
`df_redcap.fillna(value = float(np.nan), inplace = True)`

**Comment by Armin12** [comment]
Yes, Pandas dataframe stores them as numpy.float64. You can convert the dataframe to a list using df_redcap.values.tolist(), and the type of values will change to float.

**Comment by kristinksellers** [comment]
Per discussion, we will allow for floats. Add to README that 'No answer' is an option
